version: '3.9'

services:
  app:
    image: vitaliimadiakin/rlt_task:$GITHUB_RUN_ID
    container_name: rlt_api
    ports:
      - "8080:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/mongodb"
    command: bash -c "sleep 10 && mongoimport --host mongodb --db mongodb --collection sample_collection --type json --file /app/mdb_data/sample_collection.bson --jsonArray"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mdb_data:/data/db
