version: '3.9'

services:
  app:
    image: vitaliimadiakin/rlt_task:$GITHUB_RUN_ID
    container_name: api
    ports:
      - "8080:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/mongodb"

  mongodb:
    image: mongo
    container_name: mdb
    ports:
      - "27017:27017"
    volumes:
      - ./mdb_data:/data/db
